default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"].presence || ENV["PGHOST"] %>
  port: <%= ENV["DB_PORT"].presence || ENV["PGPORT"].presence || 5432 %>
  username: <%= ENV["DB_USERNAME"].presence || ENV["PGUSER"].presence || ENV.fetch("USER", "postgres") %>
  password: <%= ENV["DB_PASSWORD"].presence || ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"].presence || ENV["PGDATABASE"].presence || "dayspring_ipl_prediction_development" %>

test:
  <<: *default
  database: <%= ENV["DB_TEST_NAME"].presence || "dayspring_ipl_prediction_test" %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV["DB_NAME"].presence || ENV["PGDATABASE"].presence || "dayspring_ipl_prediction_production" %>
